### ISSUE TITLE
EMR bootstrap action not working on EMR 3.x

### ISSUE THREAD

**Issue by mrakshay** [awslabs/emr-bootstrap-actions#181]
Hello I tried running the Impala bootstrap action on EMR 4.3,4.2,4.1,4.0 & 3.11 .....but this bootstrap action worked when I executed the bootstrap action on 3.10 .....Can you please update the Impala 2.2 bootstrap action for latest versions of EMR ...possibly for EMR 4.1,4.2 ??

**Comment by mombergm** [comment]
Hi.   

The previous BA is not built to work on EMR 4.x releases. 
For the time being, I have an alpha bootstrap action that can be installed using the following aws cli command. 

aws emr create-cluster --applications Name=Hadoop Name=Hive Name=Ganglia Name=Presto-Sandbox --bootstrap-actions '[{"Path":"s3://coeus/bigtop/impala/impala-install","Name":"Provision Impala"}]' --use-default-roles --visible-to-all-users --ec2-attributes KeyName=yourKeyNameHere --instance-type r3.8xlarge --instance-count 4 --release-label emr-4.2.0

The Bootstrap action relies on you specifying Presto-Sandbox as an application. This will detect the request and install Impala instead of Presto-Sandbox. 

***PLEASE NOTE***
This is still a ***test*** and should not be used in production as is.

**Comment by mrakshay** [comment]
Thanks mombergm for updating..That didn`t work on EMR 4.1,4.2 but it worked on EMR 4.0....You are right this hasn't been used in production as I am not able to connect to the Impala shell.... Thanks a lot for updating the script

**Comment by mombergm** [comment]
Hey @mrakshay, That is quite unexpected that it would work on 4.0 as it requires the Presto Sandbox application to work. Presto-Sandbox is not available on 4.0. 

Could you please try again using 4.2, select Presto-Sandbox as an application and add the BA.

**Comment by mrakshay** [comment]
well @mombergm , As you said with EMR 4.2 & selecting Presto-Sandbox as application and then add the BA for Impala it doesn't work...Error shows **The supplied bootstrap action(s): 'Impala2 install' are not supported by release 'emr-4.2.0'.** .....is there something I am missing ??

**Comment by mombergm** [comment]
Based on the message you are getting, it doesn't seem like you are using the create cluster command I provided in my comments above. 

Could you let me know how you are creating the cluster? 
And the location of the BA you are using?

**Comment by mrakshay** [comment]
well I am not creating the cluster through AWS CLI... I am creating cluster through AWS Console UI ....& location/path of BA is "s3://coeus/bigtop/impala/impala-install" which you mentioned above...So are you creating the cluster through AWS CLI ??

**Comment by ankurmitujjain** [comment]
Any update on this?

**Comment by mrakshay** [comment]
I have tested the Impala bootstrap action on EMR 4.6..We need to add **Presto-Sandbox** as a service on EMR 4.6 and add the **s3://coeus/bigtop/impala/impala-install** as location for bootstrap action ...This works 100% on EMR 4.6 but does not work on EMR 4.7
