### ISSUE TITLE
Spark | Add support for dynamic scheduling

### ISSUE THREAD

**Issue by aniketbhatnagar** [awslabs/emr-bootstrap-actions#32]
The spark 1.2 script is missing configuration for dynamic scheduling over YARN. Dynamic scheduling requires setting up all nodes as documented in https://github.com/apache/spark/blob/master/docs/job-scheduling.md.

**Comment by christopherbozeman** [comment]
@aniketbhatnagar - can you write up a change to install-spark and/or install-spark-script.py that could support this as an optional feature?

**Comment by laszloskimlinks** [comment]
I think the followings should be added to install-spark (and placed on every node):

1. Copy `/home/hadoop/spark/lib/spark-1.4.0-yarn-shuffle.jar` `/home/hadoop/share/hadoop/yarn/lib/` (so the jar will be automatically included in `yarn.application.classpath`)
2. Add these entries to `/home/hadoop/conf/yarn-site.xml`:
<p>
```xml
   <property><name>yarn.nodemanager.aux-services</name><value>spark_shuffle</value></property>
   <property><name>yarn.nodemanager.aux-services.spark_shuffle.class</name><value>org.apache.spark.network.yarn.YarnShuffleService</value></property>
```
</p>(so we tell yarn to include spark-shuffleservice)<br>
3. Add these entries with (default) values to `/home/hadoop/spark/conf/spark-defaults.conf`:
```bash
spark.dynamicAllocation.minExecutors=1
spark.dynamicAllocation.maxExecutors=64
```
(so we have a default minimum and maximum number of used containers)<br>
When we are done with the above, we should follow up with:
  1. Restarting NodeManager on workers (slaves), or apply this configuration before launching the NodeManagers.
  2. To use dynamic allocation (DA) job-submission should look like: <br>
`spark-submit --deploy-mode client --master yarn --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true mypy.py`<br>
(optionally, we could set up either to use DA or static job-submission as default)

Notes:
  1. Realized that the number of running containers increased exponentially when using emr-spark (compared to same sized general cluster), I think it's due to the (not strictly?) defined vcores on emr-spark. When trying DA on a general cluster, the _number of running containers_ and the _number of vcores_ are in match (which seems to be a 100% resource utilization).
  2. Sometimes I received such messages at the end of a job when using spark-1.4.0.a:<br>
`INFO cluster.YarnClientSchedulerBackend: Requesting to kill executor(s) 25`<br>
`WARN cluster.YarnClientSchedulerBackend: Executor to kill 25 does not exist!`<br>
that we should handle with caution probably, but the application seemed to finish successfully, and the output was fine.

<p>
I would be curious if anybody else has experienced these notes, maybe it would worth to check it out more deeply  or verify how DA really works with emr-spark.
</p>

**Comment by jkleckner** [comment]
+1 for figuring out and supporting dynamic allocation in EMR.

**Comment by christopherbozeman** [comment]
EMR has just released EMR release 4.0.0 which includes Spark 1.4.1 and supports Spark's Dynamic Resource Allocation.

Please see https://forums.aws.amazon.com/ann.jspa?annID=3160 and 
http://docs.aws.amazon.com/ElasticMapReduce/latest/ReleaseGuide/emr-spark-configure.html#spark-dynamic-allocation

**Comment by jkleckner** [comment]
Thanks!

What is the relationship between this awslabs emr-bootstrap-actions and the release versions?
Are the release versions based on this project or are they more loosely related?

Should we now turn our focus to using those releases?

**Comment by christopherbozeman** [comment]
The EMR 4.x and native Spark on EMR versions are only loosely related as in a means to provide a solution for running Spark on EMR.  All future development and integration of Spark on EMR is now being handled separately from the Spark bootstrap action provided here.   It is highly recommended to begin to turn one's use of Spark on EMR to the native Spark as found starting with the EMR 4.x releases.
